### ISSUE TITLE
No database, no 

### ISSUE THREAD

**Issue by nexovec** [marvincorreia/superset-keycloak#6]
Hi, there is no database in your compose files. At the very least there should be one in the dev compose. You can use this:

```yaml
db:
    env_file: .env
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    volumes:
      # - db_home:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
```

there is also no keycloak there.
